# Server Settings
server:
  port: 8076
  error:
    include-message: always



eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    should-unregister-on-shutdown: false
    enabled: false  # TODO: enable eureka discovery
  instance:
    prefer-ip-address: true




api:
  service:
    user-management:
      url: "http://192.168.0.14:8106"
    orbit-user-service:
      url: "http://192.168.4.14:7000"
      endpoint:
        search: "/user-service/search"
      mock: false # if true: authenticate via db



# Database Settings
spring:
  datasource:
#    username: postgres
#    password: root
    username: system
    password: system
    url: jdbc:postgresql://localhost/isdb_sla_dev
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:/liquibase/db.changelog-master.yml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  application:
    name: sla-service
  kafka:
    bootstrap-servers: 192.168.4.14:9092 # production
#    bootstrap-servers: localhost:9092 # development


management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always
#    gateway:
#      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true


